# ChatParty Configuaration File
# invertP: Send a message to the public with /p <message> when party chat is toggled
# toggleWithP: Toggle the party chat when /p without arguments is entered (not newbie-friendly)
# messageColor: Color of the plugin messages
# chatFormat: Format of the party chat messages. Placeholders: {PARTYNAME}, {DISPLAYNAME}, {MESSAGE}
messageColor: '&a'
adminMessageColor: '&b'
partyChatFormat: '&a[P] &r{DISPLAYNAME}&a: {MESSAGE}'
adminChatFormat: '&b[A] &r{DISPLAYNAME}&b: {MESSAGE}'
NSFWChatFormat: '&4[NSFW] &r{DISPLAYNAME}&f: {MESSAGE}'
invertP: false
toggleWithP: true

lastPlayerChannel: {}
# lastPlayerChannel.UUID: party,admin,nsfw,global

parties: {}
# parties.partyname.tag: tag
# parties.partyname.players.UUID: member,leader

spy: []

censorGlobalChat: true

# Enter banned words here. There is no need to have seperate entries for 
# words seperated by puctuation, the filter should deal with that automatically.
nsfwWordFilter: []

nsfwListeners: []